#
# Run kitchen against same node.json as used by Vagrantfile
#
<%
  require 'json'
  node = JSON.parse(File.read('node.json'))

%>
---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
      ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: <%= node["run_list"] %>
    attributes: <%= node["attributes"].to_json %>
