#
# Default settings.
#
---
hexo:
  install_demo: true			# true installs a working Hexo blog with Light theme in /vagrant/demo

vm:
  hostname: hexo				# name of the virtual machine
  ip_address: 10.25.83.63		# ip-address of the virtual machine
