#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'heroku-toolbelt'

cookbook 'nodejs',
  :git => 'https://github.com/redguide/nodejs'

cookbook 'hexo',
  :git => 'https://github.com/alt3/cookbooks',
  :path => 'hexo'

cookbook 'utilities',
  :git => 'https://github.com/alt3/cookbooks',
  :path => 'utilities'
